# Capstone Project - Python Fundamentals
### Dataset: Project DataFrame, Employee DataFrame, Seniority Level DataFrame.

## Task 1 - Build the three DataFrames and make them as CSV files

In [1]:
# Importing libraries

import pandas as pd
import numpy as np

# Creating Project Dataframe

project_df = pd.DataFrame({ 
    "ID" : ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003',
            'A001', 'A003', 'A001', 'A004', 'A004', 'A005'], # employee ID for each project
    "Project": ["Project 1", "Project 2", "Project 3", "Project 4", "Project 5", "Project 6",
                "Project 7", "Project 8", "Project 9", "Project 10", "Project 11", "Project 12", "Project 13", "Project 14"], # project name
    "Cost" : [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 
              350000, np.nan, 300000, 2000000, 1000000, 3000000, 200000], # project cost, 2 missing values
    "Status" : ["Finished", "Ongoing", "Finished", "Ongoing", "Finished", "Failed", "Finished", 
                "Failed", "Ongoing", "Finished", "Failed", "Ongoing", "Finished", "Finished"] # project status
})

# Creating Employee Dataframe

employee_df = pd.DataFrame({
    "ID" : ['A001', 'A002', 'A003', 'A004', 'A005'],                                        # employee ID column
    "Name" : ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"], #employee full name column
    "Gender" : ["M", "F", "M", "F", "F"],                                                   #gender column
    "City" : ["Paris", "London", "Berlin", "Newyork", "Madrid"],                            #city column
    "Age" : [25, 27, 29, 31, 30]                                                            # age column
})       

# Creating Seniority Level Dataframe

seniority_df = pd.DataFrame({
    "ID" : ['A001', 'A002', 'A003', 'A004', 'A005'], # employee ID column, used for joining
    "Designation Level": [2, 2, 3, 2, 3]             # designation level column                           
})                            
                            
# save the Project dataframe to csv file
project_df.to_csv("Project.csv", index=False)

# save the Employee dataframe to csv file
employee_df.to_csv("Employee.csv", index=False)

# save the Seniority dataframe to csv file
seniority_df.to_csv("Seniority.csv", index=False)


# print the Project dataframe, including the missing costs values
print(project_df)

# print the Employee dataframe 
print(employee_df)

# print the Seniority
print(seniority_df)

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished
     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30
     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

## Task 2 - Filling the missing cost values with running average (using For loop)

In [2]:
# Read the Project DataFrame from the CSV saved in Task 1
project_df = pd.read_csv("Project.csv")

# Converting the 'Cost' column to numeric so we can calculate average
project_df["Cost"] = pd.to_numeric(project_df["Cost"])

# Loop through the rows to fill missing Cost values using running average
for i in range(len(project_df)):
    # If the current Cost value is NaN ( missing)
    if pd.isna(project_df.loc[i, "Cost"]):
        # Calculate running average from all previous non-missing Cost values
        running_avg = project_df.loc[:i-1, "Cost"].dropna().mean()
        # Fill the missing value with the computed running average
        project_df.loc[i, "Cost"] = running_avg

# save the updated project dataframe (with missing values filled) back to the csv file
project_df.to_csv("Project.csv", index=False)

# Display the updated DataFrame with filled Cost values
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

## Task 3 - Split Name Column in Employee DataFrame into First Name and Last Name

In [3]:
# Read the Project DataFrame from the CSV saved in Task 1
employee_df = pd.read_csv("Employee.csv")

# Split the 'Name' column into two new columns 'FirstName' and 'LastName'
employee_df[["First Name", "Last Name"]] = employee_df["Name"].str.split(' ', n=1, expand=True)

# Drop the original 'Name' column as it is replaced
employee_df = employee_df.drop(columns = ["Name"])

# save the updated employee dataframe back to the csv file
employee_df.to_csv("Employee.csv", index=False)


# Display the updated DataFrame
print(employee_df)

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

## Task 4 - Joining all the DataFrames in to one - Final

In [4]:
# Read all three updated CSV files

project_df = pd.read_csv("Project.csv")
employee_df = pd.read_csv("Employee.csv")
seniority_df = pd.read_csv("Seniority.csv")

# Merge project_df with employee_df on 'ID'
merged_df = pd.merge(project_df, employee_df, on='ID')

# Merge the result with seniority_df on 'ID'
Final = pd.merge(merged_df, seniority_df, on='ID')

# Display the combined DataFrame
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

## Task 5 - Adding a Bonus Column to Final DataBase - 5% of Cost for finished Products

In [5]:
# Define a new function to calculate Bonus

def Calculate_bonus(row):
    if row['Status'] == 'Finished': # Check if status is finished 
        return row['Cost'] * 0.05   # Calculate 5% of project cost
    else:
         return 0 # Id Status is unfinished
        
# Apply function to each row of Final DataBase
Final['Bonus'] = Final.apply(Calculate_bonus, axis=1)

# Display updated Final DataBase
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

## Task 6 - Demote Designation Level by 1 for failed projects; delete anyone above level 4

In [6]:
# Demote by 1 level where project status is 'Failed'
Final.loc[Final['Status'] == 'Failed', 'Designation Level'] += 1

# Drop employees with Designation Level > 4
Final = Final[Final['Designation Level'] <= 4]

# Display Final DataFrame with required columns to confirm
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,3,0.0
6,A005,Project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,M,Paris,25,John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000.0

## Task 7 - Add 'Mr' or 'Mrs' to  first name and drop Gender Column

In [7]:
# Adding Prefix to First Name

for i in Final.index:
     if Final.loc[i, "Gender"] == "M":  
         Final.loc[i, "First Name"] = "Mr. " + Final.loc[i, "First Name"] # add the "Mr." title in front of the first name
     else:
         Final.loc[i, "First Name"] = "Mrs. " + Final.loc[i, "First Name"] # add "Mrs." in front of the first name for non-male records

# drop the gender column 
Final = Final.drop(columns=["Gender"])

# Display updated Final DataFrame
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.0

## Task 8 - Promote Designation Level by 1 for employees older than 29 using IF

In [8]:
# Loop through every row for Final DataFrame using 

for i in Final.index:
    if Final.loc[i, 'Age'] > 29: # Step 2: Check if Age > 29
        Final.loc[i, 'Designation Level'] -= 1  # Increase Designation Level by 1

# Display updated Final DataFrame
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
4,A005,Project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,2,162525.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,0.0
6,A005,Project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,2,20000.0
7,A003,Project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0
13,A005,Project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,2,10000.0

## Task 9 - Create \"TotalProjCost\" for each Employee

In [9]:
# group the Final dataframe by ID and First Name, then add up the Cost column

TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# rename the summed "Cost" column to "Total Cost" for clarity

TotalProjCost = TotalProjCost.rename(columns={"Cost": "Total Cost"})

# Display the new TotalProjCost dataframe with required columns
TotalProjCost

     ID  First Name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

## Task 10 - Print Employees whose City name contains letter \"o\"

In [10]:
# Filter rows where 'City' contains the letter 'o'
employees_with_o_city = Final[Final['City'].str.contains('o', case=False, na=False)]

# Print the updated result
employees_with_o_city

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0